[package]
name = "bifrost"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
anyhow = "1.0.79"
hex = "0.4.3"
nanoid = "0.4.0"
redis = "0.24.0"
ring = "0.17.7"
serde = { version = "1.0.196", features = ["derive"] }
